image:
  - Visual Studio 2019

platform:
  - x64

configuration:
  - Debug
# - Release

clone_folder: c:/projects/NinGine

build_script:
- cd c:/projects/NinGine/Ningine
- mkdir build
- cd build
- cmake -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake c:/projects/NinGine/Ningine -G "Visual Studio 16"
- cmake --build .

install:
- cd c:/Tools/vcpkg 
- vcpkg integrate install
- vcpkg install glfw3:x64-windows glad:x64-windows glm:x64-windows opencl:x64-windows

cache: c:/tools/vcpkg/installed/

notifications:
- provider: Email
  to:
  - '{{commitAuthorEmail}}'
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false